// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Redirect struct {
	ID        int32
	ShortCode string
	UrlID     sql.NullInt32
	CreatedAt sql.NullTime
}

type Url struct {
	ID          int32
	OriginalUrl string
	CreatedAt   sql.NullTime
}
