// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Url struct {
	ID          int64
	ShortCode   sql.NullString
	OriginalUrl string
	ClickCount  sql.NullInt32
	CreatedAt   sql.NullTime
}
